export enum CONFIGURATION {
  // environment
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  // mysql prisma
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_OPTION = 'MYSQL_OPTION',
  // connection string prisma
  MYSQL_URL = 'MYSQL_URL',
  // MailChimp
  MAILCHIMP_API_KEY = 'MAILCHIMP_API_KEY',
  MAILCHIMP_AUDIENCE_ID = 'MAILCHIMP_AUDIENCE_ID',
  MAILCHIMP_URI = 'MAILCHIMP_URI',
  MAILCHIMP_USERNAME = 'MAILCHIMP_USERNAME',
  // JWT and Authentication
  JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
  JWT_TOKEN_PUBLIC_SECRET_KEY = 'JWT_TOKEN_PUBLIC_SECRET_KEY',
  JWT_REFRESH_TOKEN_SECRET_KEY = 'JWT_REFRESH_TOKEN_SECRET_KEY',
  JWT_ACCESS_TOKEN_TIME_TO_LIVE = 'JWT_ACCESS_TOKEN_TIME_TO_LIVE',
  JWT_REFRESH_TOKEN_TIME_TO_LIVE = 'JWT_REFRESH_TOKEN_TIME_TO_LIVE',
  TWO_FACTOR_AUTH_SECRET_KEY = 'TWO_FACTOR_AUTH_SECRET_KEY',
  PASSWORD_SALT_STATIC = 'PASSWORD_SALT_STATIC',
  // websocket
  WEBSOCKET_URL = 'WEBSOCKET_URL',
  // Google services
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  ASSETS_EXPIRES = 'ASSETS_EXPIRES',
  GOOGLE_CALENDAR_KEY = 'GOOGLE_CALENDAR_KEY',
  // REDIS
  REDIS_TIME_LIFE_CACHING = 'REDIS_TIME_LIFE_CACHING',
  REDIS_TIME_LIFE_CATCHING_RESEND_2FA = 'REDIS_TIME_LIFE_CATCHING_RESEND_2FA',
}
