export const ROLE = {
  DIRECTOR: 1,
  //
  CS_MANAGER: 12,
  CS_LEADER: 20,
  CS_MEMBER: 13,
  //
  ACCOUNTANT_MANAGER: 41,
  ACCOUNTANT_LEADER: 16,
  ACCOUNTANT_MEMBER: 17,
  //
  COMPLIANCE_LEADER: 19,
  COMPLIANCE_MEMBER: 22,
  //
  INTERNAL_BOOKKEEPER_MEMBER: 21,
  INTERNAL_BOOKKEEPER_LEADER: 34,
  //
  LEGAL_LEADER: 23,
  LEGAL_MEMBER: 24,

  RD_MANAGER: 39,
  CUSTOMER: 18,

  COMPLIANCE: 19,
  INTERNAL_BOOKKEEPER: 21,

  CS_LEADER_1: 20,
  CS_LEADER_2: 35,
  CS_LEADER_3: 36,
  CS_MEMBER_1: 13,
  CS_MEMBER_2: 37,
  CS_MEMBER_3: 38,
  CS_LEADER_4: 51,
  CS_LEADER_5: 52,
  CS_MEMBER_4: 53,
  CS_MEMBER_5: 54,

  TESTER_MEMBER: 6,
  TESTER_LEADER: 25,
};

export const ROLE_VALUE = {
  DIRECTOR: 'DIRECTOR',
  VICE_DIRECTOR: 'VICE_DIRECTOR',
  IT_MANAGER: 'IT_MANAGER',
  BACKEND_LEADER: 'BACKEND_LEADER',
  BACKEND_DEVELOPER: 'BACKEND_DEVELOPER',
  TESTER_MEMBER: 'TESTER_MEMBER',
  SYSTEM_SECURITY: 'SYSTEM_SECURITY',
  HR_MANAGER: 'HR_MANAGER',
  HR_STAFF: 'HR_STAFF',
  CS_MANAGER: 'CS_MANAGER',
  CS_MEMBER: 'CS_MEMBER',
  RMD_MANAGER: 'RMD_MANAGER',
  RMD_MEMBER: 'RMD_MEMBER',
  ACCOUNTANT_LEADER: 'ACCOUNTANT_LEADER',
  ACCOUNTANT_MEMBER: 'ACCOUNTANT_MEMBER',
  CUSTOMER: 'CUSTOMER',
  COMPLIANCE_LEADER: 'COMPLIANCE_LEADER',
  CS_LEADER: 'CS_LEADER',
  BOOKKEEPER_MEMBER: 'BOOKKEEPER_MEMBER',
  COMPLIANCE_MEMBER: 'COMPLIANCE_MEMBER',
  LEGAL_LEADER: 'LEGAL_LEADER',
  LEGAL_MEMBER: 'LEGAL_MEMBER',
  TESTER_LEADER: 'TESTER_LEADER',
  FE_LEADER: 'FE_LEADER',
  FE_DEVELOPER: 'FE_DEVELOPER',
  SYSTEM_LEADER: 'SYSTEM_LEADER',
  BA_LEADER: 'BA_LEADER',
  BOOKKEEPER_LEADER: 'BOOKKEEPER_LEADER',
  RD_MANAGER: 'RD_MANAGER',
  ACCOUNTANT_MANAGER: 'ACCOUNTANT_MANAGER',
};
