export enum ATTRIBUTE_DEFAULT {
  id = 'id',
  createdTime = 'createdTime',
  updatedTime = 'updatedTime',
  deletedTime = 'deletedTime',
  isDeleted = 'isDeleted',
}

export enum COLUMN_DEFAULT {
  id = 'id',
  createdTime = 'created_time',
  updatedTime = 'updated_time',
  deletedTime = 'deleted_time',
  isDeleted = 'is_deleted',
}

export enum RELATION_DEFAULT {
  syslogs = 'syslogs',
  apis = 'apis',
  user = 'user',
  task = 'task',
  agents = 'agents',
  agency = 'agency',
  customers = 'customers',
  services = 'services',
  visaOrders = 'visaOrders',
  bank = 'bank',
  country = 'country',
  agentType = 'agentType',
  emails = 'emails',
  processLogs = 'processLogs',
  taskHasAgents = 'taskHasAgents',
  tokens = 'tokens',
  billings = 'billings',
  processes = 'processes',
  actionProcessSteps = 'actionProcessSteps',
  historyLogCDCs = 'historyLogCDCs',
  notificationTemplates = 'notificationTemplates',
  companyMember = 'companyMember',
  option = 'option',
  question = 'question',
  company = 'company',
  apiMethod = 'apiMethod',
  apiExamples = 'apiExamples',
  apiHasFields = 'apiHasFields',
  apiHasGroups = 'apiHasGroups',
  apiStatus = 'apiStatus',
  apiGroup = 'apiGroup',
  api = 'api',
  files = 'files',
  bankBranches = 'bankBranches',
  bankHasCountries = 'bankHasCountries',
  bankHasFileTemplates = 'bankHasFileTemplates',
  bankHasKeywords = 'bankHasKeywords',
  bankingProcesses = 'bankingProcesses',
  customerHasBanks = 'customerHasBanks',
  orderHasBanks = 'orderHasBanks',
}
