import { ATTRIBUTE_DEFAULT, COLUMN_DEFAULT, RELATION_DEFAULT } from './default';

export enum ATTRIBUTE {
  id = 'id',
  customerId = 'customerId',
  companyId = 'companyId',
  amount = 'amount',
  amountConverted = 'amountConverted',
  amountCode = 'amountCode',
  amountExchangeRate = 'amountExchangeRate',
  paidAmount = 'paidAmount',
  refundAmount = 'refundAmount',
  discount = 'discount',
  creditAmount = 'creditAmount',
  creditDescription = 'creditDescription',
  annualFee = 'annualFee',
  isInvoiced = 'isInvoiced',
  orderCode = 'orderCode',
  xeroInvoiceId = 'xeroInvoiceId',
  paymentGatewayId = 'paymentGatewayId',
  paypalOrderId = 'paypalOrderId',
  paypalInvoiceId = 'paypalInvoiceId',
  xeroInvoiceStatusId = 'xeroInvoiceStatusId',
  xeroInvoiceUrl = 'xeroInvoiceUrl',
  xeroInvoiceNo = 'xeroInvoiceNo',
  orderStatusId = 'orderStatusId',
  paidTime = 'paidTime',
  websiteId = 'websiteId',
  billingId = 'billingId',
  orderFromId = 'orderFromId',
  countryCardId = 'countryCardId',
  createdTime = ATTRIBUTE_DEFAULT.createdTime,
  updatedTime = ATTRIBUTE_DEFAULT.updatedTime,
  deletedTime = ATTRIBUTE_DEFAULT.deletedTime,
  isDeleted = ATTRIBUTE_DEFAULT.isDeleted,
}

export enum COLUMN {
  id = 'id',
  customerId = 'customer_id',
  companyId = 'company_id',
  amount = 'amount',
  amountConverted = 'amount_converted',
  amountCode = 'amount_code',
  amountExchangeRate = 'amount_exchange_rate',
  paidAmount = 'paid_amount',
  refundAmount = 'refund_amount',
  discount = 'discount',
  creditAmount = 'credit_amount',
  creditDescription = 'credit_description',
  annualFee = 'annual_fee',
  isInvoiced = 'is_invoiced',
  orderCode = 'order_code',
  xeroInvoiceId = 'xero_invoice_id',
  paymentGatewayId = 'payment_gateway_id',
  paypalOrderId = 'paypal_order_id',
  paypalInvoiceId = 'paypal_invoice_id',
  xeroInvoiceStatusId = 'xero_invoice_status_id',
  xeroInvoiceUrl = 'xero_invoice_url',
  xeroInvoiceNo = 'xero_invoice_no',
  orderStatusId = 'order_status_id',
  paidTime = 'paid_time',
  websiteId = 'website_id',
  billingId = 'billing_id',
  orderFromId = 'order_from_id',
  countryCardId = 'country_card_id',
  createdTime = COLUMN_DEFAULT.createdTime,
  updatedTime = COLUMN_DEFAULT.updatedTime,
  deletedTime = COLUMN_DEFAULT.deletedTime,
  isDeleted = COLUMN_DEFAULT.isDeleted,
}

export enum RELATION {
  billing = RELATION_DEFAULT.billing,
  company = RELATION_DEFAULT.company,
  // customerOrderCustomerIdToCustomer = RELATION_DEFAULT.customerOrderCustomerIdToCustomer,
  orderStatus = RELATION_DEFAULT.orderStatus,
  // paymentGateway = RELATION_DEFAULT.paymentGateway,
  website = RELATION_DEFAULT.website,
  // xeroInvoiceStatus = RELATION_DEFAULT.xeroInvoiceStatus,
  country = RELATION_DEFAULT.country,
  // orderFromIdOrderOrderFromIdToOrderFromId = RELATION_DEFAULT.orderFromIdOrderOrderFromIdToOrderFromId,
  companyEvent = RELATION_DEFAULT.companyEvent,
  // customerCustomerOrderIdToOrder = RELATION_DEFAULT.customerCustomerOrderIdToOrder,
  file = RELATION_DEFAULT.file,
  orderHasBanks = RELATION_DEFAULT.orderHasBanks,
  // orderItems = RELATION_DEFAULT.orderItems,
  // paymentsInformation = RELATION_DEFAULT.paymentsInformation,
  // supportCaseHasOrder = RELATION_DEFAULT.supportCaseHasOrders,
  // taskTaskOrderIdToOrder = RELATION_DEFAULT.taskTaskOrderIdToOrder,
  // taskTaskUpgradeOrderIdToOrder = RELATION_DEFAULT.taskTaskUpgradeOrderIdToOrder,
  visaOrders = RELATION_DEFAULT.visaOrders,
  // vouchers = RELATION_DEFAULT.vouchers,
}

export enum INDEX {
  billingId = `@@index([${ATTRIBUTE.billingId}], map: "fk_ord_billing_id_bil_id_7408")`,
  companyId = `@@index([${ATTRIBUTE.companyId}], map: "fk_ord_company_id_com_id_3fyj")`,
  customerId = `@@index([${ATTRIBUTE.customerId}], map: "fk_ord_customer_id_cus_id_a3fz")`,
  orderStatusId = `@@index([${ATTRIBUTE.orderStatusId}], map: "fk_ord_order_status_id_ord_id_j2rt")`,
  paymentGatewayId = `@@index([${ATTRIBUTE.paymentGatewayId}], map: "fk_ord_payment_gateway_id_pay_id_eysq")`,
  websiteId = `@@index([${ATTRIBUTE.websiteId}], map: "fk_ord_website_id_web_id_e77e")`,
  xeroInvoiceStatusId = `@@index([${ATTRIBUTE.xeroInvoiceStatusId}], map: "fk_ord_xero_invoice_status_id_xer_id_46g8")`,
  countryCardId = `@@index([${ATTRIBUTE.countryCardId}], map: "fk_order_country_card_id_idx")`,
  orderFromId = `@@index([${ATTRIBUTE.orderFromId}], map: "fk_order_from_id_idx")`,
}

export default {
  ATTRIBUTE,
  RELATION,
};
