import { TABLE_NAME } from '../constants';
import { ATTRIBUTE_DEFAULT, COLUMN_DEFAULT, RELATION_DEFAULT } from './default';

export enum ATTRIBUTE {
  id = 'id',
  customerId = 'customerId',
  companyId = 'companyId',
  amount = 'amount',
  amountConverted = 'amountConverted',
  amountCode = 'amountCode',
  amountExchangeRate = 'amountExchangeRate',
  paidAmount = 'paidAmount',
  refundAmount = 'refundAmount',
  discount = 'discount',
  creditAmount = 'creditAmount',
  creditDescription = 'creditDescription',
  annualFee = 'annualFee',
  isInvoiced = 'isInvoiced',
  orderCode = 'orderCode',
  xeroInvoiceId = 'xeroInvoiceId',
  paymentGatewayId = 'paymentGatewayId',
  paypalOrderId = 'paypalOrderId',
  paypalInvoiceId = 'paypalInvoiceId',
  xeroInvoiceStatusId = 'xeroInvoiceStatusId',
  xeroInvoiceUrl = 'xeroInvoiceUrl',
  xeroInvoiceNo = 'xeroInvoiceNo',
  orderStatusId = 'orderStatusId',
  paidTime = 'paidTime',
  websiteId = 'websiteId',
  billingId = 'billingId',
  orderFromId = 'orderFromId',
  countryCardId = 'countryCardId',
  createdTime = ATTRIBUTE_DEFAULT.createdTime,
  updatedTime = ATTRIBUTE_DEFAULT.updatedTime,
  deletedTime = ATTRIBUTE_DEFAULT.deletedTime,
  isDeleted = ATTRIBUTE_DEFAULT.isDeleted,
}

export enum COLUMN {
  id = 'id',
  customerId = 'customer_id',
  companyId = 'company_id',
  amount = 'amount',
  amountConverted = 'amount_converted',
  amountCode = 'amount_code',
  amountExchangeRate = 'amount_exchange_rate',
  paidAmount = 'paid_amount',
  refundAmount = 'refund_amount',
  discount = 'discount',
  creditAmount = 'credit_amount',
  creditDescription = 'credit_description',
  annualFee = 'annual_fee',
  isInvoiced = 'is_invoiced',
  orderCode = 'order_code',
  xeroInvoiceId = 'xero_invoice_id',
  paymentGatewayId = 'payment_gateway_id',
  paypalOrderId = 'paypal_order_id',
  paypalInvoiceId = 'paypal_invoice_id',
  xeroInvoiceStatusId = 'xero_invoice_status_id',
  xeroInvoiceUrl = 'xero_invoice_url',
  xeroInvoiceNo = 'xero_invoice_no',
  orderStatusId = 'order_status_id',
  paidTime = 'paid_time',
  websiteId = 'website_id',
  billingId = 'billing_id',
  orderFromId = 'order_from_id',
  countryCardId = 'country_card_id',
  createdTime = COLUMN_DEFAULT.createdTime,
  updatedTime = COLUMN_DEFAULT.updatedTime,
  deletedTime = COLUMN_DEFAULT.deletedTime,
  isDeleted = COLUMN_DEFAULT.isDeleted,
}

export enum RELATION {
  companyEvents = RELATION_DEFAULT.companyEvents,
  customers = RELATION_DEFAULT.customers,
  files = RELATION_DEFAULT.files,
  billing = RELATION_DEFAULT.billing,
  company = RELATION_DEFAULT.company,
  customer = RELATION_DEFAULT.customer,
  orderStatus = RELATION_DEFAULT.orderStatus,
  paymentGateway = RELATION_DEFAULT.paymentGateway,
  website = RELATION_DEFAULT.website,
  xeroInvoiceStatus = RELATION_DEFAULT.xeroInvoiceStatus,
  countryCard = RELATION_DEFAULT.countryCard,
  orderFrom = RELATION_DEFAULT.orderFrom,
  banks = RELATION_DEFAULT.banks,
  orderItems = RELATION_DEFAULT.orderItems,
  paymentsInformation = RELATION_DEFAULT.paymentsInformation,
  supportCases = RELATION_DEFAULT.supportCases,
  tasks = RELATION_DEFAULT.tasks,
  upgradeOrderTasks = RELATION_DEFAULT.upgradeOrderTasks,
  visaOrders = RELATION_DEFAULT.visaOrders,
  vouchers = RELATION_DEFAULT.vouchers,
}

const tableName = TABLE_NAME.ORDER;
export enum INDEX_NAME {
  billingId = `"${tableName}_${COLUMN.billingId}_fkey"`,
  companyId = `"${tableName}_${COLUMN.companyId}_fkey"`,
  customerId = `"${tableName}_${COLUMN.customerId}_fkey"`,
  orderStatusId = `"${tableName}_${COLUMN.orderStatusId}_fkey"`,
  paymentGatewayId = `"${tableName}_${COLUMN.paymentGatewayId}_fkey"`,
  websiteId = `"${tableName}_${COLUMN.websiteId}_fkey"`,
  xeroInvoiceStatusId = `"${tableName}_${COLUMN.xeroInvoiceStatusId}_fkey"`,
  countryCardId = `"${tableName}_${COLUMN.countryCardId}_fkey"`,
  orderFromId = `"${tableName}_${COLUMN.orderFromId}_fkey"`,
}

export enum INDEX {
  billingId = `@@index([${ATTRIBUTE.billingId}], map: ${INDEX_NAME.billingId})`,
  companyId = `@@index([${ATTRIBUTE.companyId}], map: ${INDEX_NAME.companyId})`,
  customerId = `@@index([${ATTRIBUTE.customerId}], map: ${INDEX_NAME.customerId})`,
  orderStatusId = `@@index([${ATTRIBUTE.orderStatusId}], map: ${INDEX_NAME.orderStatusId})`,
  paymentGatewayId = `@@index([${ATTRIBUTE.paymentGatewayId}], map: ${INDEX_NAME.paymentGatewayId})`,
  websiteId = `@@index([${ATTRIBUTE.websiteId}], map: ${INDEX_NAME.websiteId})`,
  xeroInvoiceStatusId = `@@index([${ATTRIBUTE.xeroInvoiceStatusId}], map: ${INDEX_NAME.xeroInvoiceStatusId})`,
  countryCardId = `@@index([${ATTRIBUTE.countryCardId}], map: ${INDEX_NAME.countryCardId})`,
  orderFromId = `@@index([${ATTRIBUTE.orderFromId}], map: ${INDEX_NAME.orderFromId})`,
}

export default {
  ATTRIBUTE,
  RELATION,
};
