import { ATTRIBUTE_DEFAULT, COLUMN_DEFAULT, RELATION_DEFAULT } from './default';

export enum ATTRIBUTE {
  id = 'id',
  customerId = 'customerId',
  companyId = 'companyId',
  orderId = 'orderId',
  upgradeOrderId = 'upgradeOrderId',
  fullName = 'fullName',
  phone = 'phone',
  email = 'email',
  address = 'address',
  entityTypeId = 'entityTypeId',
  countryId = 'countryId',
  incorporationCountryId = 'incorporationCountryId',
  isRemindClientContact = 'isRemindClientContact',
  isRemindAgentCheckName = 'isRemindAgentCheckName',
  isRemindClientSignOrder = 'isRemindClientSignOrder',
  isRemindAgentCheckDocument = 'isRemindAgentCheckDocument',
  isRemindClientSignDocument = 'isRemindClientSignDocument',
  isRemindAgentCheckOriginDocument = 'isRemindAgentCheckOriginDocument',
  isRemindClientCheckName = 'isRemindClientCheckName',
  isRemindAgentReviewBusinessPlanForm = 'isRemindAgentReviewBusinessPlanForm',
  isRemindAgentReviewApplicationSet = 'isRemindAgentReviewApplicationSet',
  isRemindClientReviewApplicationSet = 'isRemindClientReviewApplicationSet',
  isRemindClientDeposit = 'isRemindClientDeposit',
  isRemindAgentReviewApplicationForm = 'isRemindAgentReviewApplicationForm',
  isRemindClientReviewApplicationForm = 'isRemindClientReviewApplicationForm',
  isRemindAgentReviewScheduleMeeting = 'isRemindAgentReviewScheduleMeeting',
  isRemindClientScheduleMeeting = 'isRemindClientScheduleMeeting',
  phoneCountryId = 'phoneCountryId',
  phoneNumber = 'phoneNumber',
  state = 'state',
  city = 'city',
  postalCode = 'postalCode',
  appointedShareholderCompanyMemberId = 'appointedShareholderCompanyMemberId',
  appointedDirectorCompanyMemberId = 'appointedDirectorCompanyMemberId',
  appointedUboCompanyMemberId = 'appointedUboCompanyMemberId',
  appointedPresidentCompanyMemberId = 'appointedPresidentCompanyMemberId',
  isFinished = 'isFinished',
  isBankingFinished = 'isBankingFinished',
  isRemindAgentServiceRequestRoundChop = 'isRemindAgentServiceRequestRoundChop',
  isRemindAgentServiceRequestCertification = 'isRemindAgentServiceRequestCertification',
  isRemindAgentServiceRequestCourier = 'isRemindAgentServiceRequestCourier',
  reasonUseNomineeDirector = 'reasonUseNomineeDirector',
  reasonUseNomineeShareholder = 'reasonUseNomineeShareholder',
  isNoteCompliance = 'isNoteCompliance',
  csLeaderId = 'csLeaderId',
  csMemberId = 'csMemberId',
  accountantLeaderId = 'accountantLeaderId',
  accountantMemberId = 'accountantMemberId',
  legalLeaderId = 'legalLeaderId',
  legalMemberId = 'legalMemberId',
  complianceLeaderId = 'complianceLeaderId',
  complianceMemberId = 'complianceMemberId',
  internalBookeepingLeaderId = 'internalBookeepingLeaderId',
  internalBookeepingMemberId = 'internalBookeepingMemberId',
  testerLeaderId = 'testerLeaderId',
  timeUnassignedTester = 'timeUnassignedTester',
  createdTime = ATTRIBUTE_DEFAULT.createdTime,
  updatedTime = ATTRIBUTE_DEFAULT.updatedTime,
  deletedTime = ATTRIBUTE_DEFAULT.deletedTime,
  isDeleted = ATTRIBUTE_DEFAULT.isDeleted,
}

export enum COLUMN {
  id = 'id',
  customerId = 'customer_id',
  companyId = 'company_id',
  orderId = 'order_id',
  upgradeOrderId = 'upgrade_order_id',
  fullName = 'full_name',
  phone = 'phone',
  email = 'email',
  address = 'address',
  entityTypeId = 'entity_type_id',
  countryId = 'country_id',
  incorporationCountryId = 'incorporation_country_id',
  isRemindClientContact = 'is_remind_client_contact',
  isRemindAgentCheckName = 'is_remind_agent_check_name',
  isRemindClientSignOrder = 'is_remind_client_sign_order',
  isRemindAgentCheckDocument = 'is_remind_agent_check_document',
  isRemindClientSignDocument = 'is_remind_client_sign_document',
  isRemindAgentCheckOriginDocument = 'is_remind_agent_check_orign_document',
  isRemindClientCheckName = 'is_remind_client_check_name',
  isRemindAgentReviewBusinessPlanForm = 'is_remind_agent_review_business_plan_form',
  isRemindAgentReviewApplicationSet = 'is_remind_agent_review_application_set',
  isRemindClientReviewApplicationSet = 'is_remind_client_review_application_set',
  isRemindClientDeposit = 'is_remind_client_deposit',
  isRemindAgentReviewApplicationForm = 'is_remind_agent_review_application_form',
  isRemindClientReviewApplicationForm = 'is_remind_client_review_application_form',
  isRemindAgentReviewScheduleMeeting = 'is_remind_agent_review_schedule_meeting',
  isRemindClientScheduleMeeting = 'is_remind_client_schedule_meeting',
  phoneCountryId = 'phone_country_id',
  phoneNumber = 'phone_number',
  state = 'state',
  city = 'city',
  postalCode = 'postal_code',
  appointedShareholderCompanyMemberId = 'appointed_shareholder_company_member_id',
  appointedDirectorCompanyMemberId = 'appointed_director_company_member_id',
  appointedUboCompanyMemberId = 'appointed_ubo_company_member_id',
  appointedPresidentCompanyMemberId = 'appointed_president_company_member_id',
  isFinished = 'is_finished',
  isBankingFinished = 'is_banking_finished',
  isRemindAgentServiceRequestRoundChop = 'is_remind_agent_service_request_round_chop',
  isRemindAgentServiceRequestCertification = 'is_remind_agent_service_request_certification',
  isRemindAgentServiceRequestCourier = 'is_remind_agent_service_request_courier',
  reasonUseNomineeDirector = 'reason_use_nominee_director',
  reasonUseNomineeShareholder = 'reason_use_nominee_shareholder',
  isNoteCompliance = 'is_note_compliance',
  csLeaderId = 'cs_leader_id',
  csMemberId = 'cs_member_id',
  accountantLeaderId = 'accountant_leader_id',
  accountantMemberId = 'accountant_member_id',
  legalLeaderId = 'legal_leader_id',
  legalMemberId = 'legal_member_id',
  complianceLeaderId = 'compliance_leader_id',
  complianceMemberId = 'compliance_member_id',
  internalBookeepingLeaderId = 'internal_bookeeping_leader_id',
  internalBookeepingMemberId = 'internal_bookeeping_member_id',
  testerLeaderId = 'tester_leader_id',
  timeUnassignedTester = 'time_unassigned_tester',
  createdTime = COLUMN_DEFAULT.createdTime,
  updatedTime = COLUMN_DEFAULT.updatedTime,
  deletedTime = COLUMN_DEFAULT.deletedTime,
  isDeleted = COLUMN_DEFAULT.isDeleted,
}

export enum RELATION {
  userTaskAccountantLeaderIdTouser = RELATION_DEFAULT.user,
  userTaskAccountantMemberIdTouser = RELATION_DEFAULT.user,
  companyMemberTaskAppointedDirectorCompanyMemberIdTocompanyMember = RELATION_DEFAULT.companyMember,
  companyMemberTaskAppointedPresidentCompanyMemberIdTocompanyMember = RELATION_DEFAULT.companyMember,
  companyMemberTaskAppointedShareholderCompanyMemberIdTocompanyMember = RELATION_DEFAULT.companyMember,
  companyMemberTaskAppointedUboCompanyMemberIdTocompanyMember = RELATION_DEFAULT.companyMember,
  company = RELATION_DEFAULT.company,
  userTaskComplianceLeaderIdTouser = RELATION_DEFAULT.user,
  userTaskComplianceMemberIdTouser = RELATION_DEFAULT.user,
  countryTaskCountryIdTocountry = RELATION_DEFAULT.country,
  userTaskCsLeaderIdTouser = RELATION_DEFAULT.user,
  userTaskCsMemberIdTouser = RELATION_DEFAULT.user,
  customer = RELATION_DEFAULT.customer,
  entityType = RELATION_DEFAULT.entityType,
  countryTaskIncorporationCountryIdTocountry = RELATION_DEFAULT.country,
  userTaskInternalBookeepingLeaderIdTouser = RELATION_DEFAULT.user,
  userTaskInternalBookeepingMemberIdTouser = RELATION_DEFAULT.user,
  userTaskLegalLeaderIdTouser = RELATION_DEFAULT.user,
  userTaskLegalMemberIdTouser = RELATION_DEFAULT.user,
  orderTaskOrderIdToorder = RELATION_DEFAULT.order,
  countryTaskPhoneCountryIdTocountry = RELATION_DEFAULT.country,
  orderTaskUpgradeOrderIdToorder = RELATION_DEFAULT.order,
  userTaskTesterLeaderIdTouser = RELATION_DEFAULT.user,
}

export enum INDEX {
  accountantLeaderId = `@@index([${ATTRIBUTE.accountantLeaderId}], map: "fk_tas_accountant_leader_id_use_id_jg1p")`,
  accountantMemberId = `@@index([${ATTRIBUTE.accountantMemberId}], map: "fk_tas_accountant_member_id_use_id_d12h")`,
  appointedDirectorCompanyMemberId = `@@index([${ATTRIBUTE.appointedDirectorCompanyMemberId}], map: "fk_tas_appointed_director_company_member_id_com_id_ht5c")`,
  appointedPresidentCompanyMemberId = `@@index([${ATTRIBUTE.appointedPresidentCompanyMemberId}], map: "fk_tas_appointed_president_company_member_id_com_id_2ves")`,
  appointedShareholderCompanyMemberId = `@@index([${ATTRIBUTE.appointedShareholderCompanyMemberId}], map: "fk_tas_appointed_shareholder_company_member_id_com_id_3k03")`,
  appointedUboCompanyMemberId = `@@index([${ATTRIBUTE.appointedUboCompanyMemberId}], map: "fk_tas_appointed_ubo_company_member_id_com_id_ee2u")`,
  companyId = `@@index([${ATTRIBUTE.companyId}], map: "fk_tas_company_id_com_id_j3cp")`,
  complianceLeaderId = `@@index([${ATTRIBUTE.complianceLeaderId}], map: "fk_tas_compliance_leader_id_use_id_3dl1")`,
  complianceMemberId = `@@index([${ATTRIBUTE.complianceMemberId}], map: "fk_tas_compliance_member_id_use_id_kqi2")`,
  countryId = `@@index([${ATTRIBUTE.countryId}], map: "fk_tas_country_id_cou_id_caag")`,
  csLeaderId = `@@index([${ATTRIBUTE.csLeaderId}], map: "fk_tas_cs_leader_id_use_id_guom")`,
  csMemberId = `@@index([${ATTRIBUTE.csMemberId}], map: "fk_tas_cs_member_id_use_id_50y8")`,
  customerId = `@@index([${ATTRIBUTE.customerId}], map: "fk_tas_customer_id_cus_id_5fep")`,
  entityTypeId = `@@index([${ATTRIBUTE.entityTypeId}], map: "fk_tas_entity_type_id_ent_id_crjn")`,
  incorporationCountryId = `@@index([${ATTRIBUTE.incorporationCountryId}], map: "fk_tas_incorporation_country_id_cou_id_73ul")`,
  internalBookeepingLeaderId = `@@index([${ATTRIBUTE.internalBookeepingLeaderId}], map: "fk_tas_internal_bookeeping_leader_id_use_id_bx56")`,
  internalBookeepingMemberId = `@@index([${ATTRIBUTE.internalBookeepingMemberId}], map: "fk_tas_internal_bookeeping_member_id_use_id_c7t9")`,
  legalLeaderId = `@@index([${ATTRIBUTE.legalLeaderId}], map: "fk_tas_legal_leader_id_use_id_fnn2")`,
  legalMemberId = `@@index([${ATTRIBUTE.legalMemberId}], map: "fk_tas_legal_member_id_use_id_1sn7")`,
  orderId = `@@index([${ATTRIBUTE.orderId}], map: "fk_tas_order_id_ord_id_ber2")`,
  phoneCountryId = `@@index([${ATTRIBUTE.phoneCountryId}], map: "fk_tas_phone_country_id_cou_id_9z9u")`,
  upgradeOrderId = `@@index([${ATTRIBUTE.upgradeOrderId}], map: "fk_tas_upgrade_order_id_ord_id_1gdh")`,
  testerLeaderId = `@@index([${ATTRIBUTE.testerLeaderId}], map: "fk_task_tester_leader_id_idx")`,
}

export default {
  ATTRIBUTE,
  RELATION,
};
